name: scandit_flutter_datacapture_label_text
description: This plugin enables Barcode Semantics capabilities.
version: 8.1.0
homepage: https://scandit.com

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.label_text
        pluginClass: ScanditFlutterDataCaptureLabelTextPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureLabelTextPlugin
